Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/nbclient/client.py", line 608, in async_setup_kernel
    yield
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
modell = DecisionTreeClassifier(criterion='entropy')

plot_tree(modell, 
    feature_names=['Kilometerstand [km]', 'Preis [EUR]'],
    class_names=['nicht verkauft', 'verkauft']);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNotFittedError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 3[0m
[1;32m      1[0m modell [38;5;241m=[39m DecisionTreeClassifier(criterion[38;5;241m=[39m[38;5;124m'[39m[38;5;124mentropy[39m[38;5;124m'[39m)
[0;32m----> 3[0m plot_tree(modell, 
[1;32m      4[0m     feature_names[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mKilometerstand [km][39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mPreis [EUR][39m[38;5;124m'[39m],
[1;32m      5[0m     class_names[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mnicht verkauft[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mverkauft[39m[38;5;124m'[39m])

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/sklearn/utils/_param_validation.py:211[0m, in [0;36mvalidate_params.<locals>.decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    205[0m [38;5;28;01mtry[39;00m:
[1;32m    206[0m     [38;5;28;01mwith[39;00m config_context(
[1;32m    207[0m         skip_parameter_validation[38;5;241m=[39m(
[1;32m    208[0m             prefer_skip_nested_validation [38;5;129;01mor[39;00m global_skip_validation
[1;32m    209[0m         )
[1;32m    210[0m     ):
[0;32m--> 211[0m         [38;5;28;01mreturn[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    212[0m [38;5;28;01mexcept[39;00m InvalidParameterError [38;5;28;01mas[39;00m e:
[1;32m    213[0m     [38;5;66;03m# When the function is just a wrapper around an estimator, we allow[39;00m
[1;32m    214[0m     [38;5;66;03m# the function to delegate validation to the estimator, but we replace[39;00m
[1;32m    215[0m     [38;5;66;03m# the name of the estimator by the name of the function in the error[39;00m
[1;32m    216[0m     [38;5;66;03m# message to avoid confusion.[39;00m
[1;32m    217[0m     msg [38;5;241m=[39m re[38;5;241m.[39msub(
[1;32m    218[0m         [38;5;124mr[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;124m\[39m[38;5;124mw+ must be[39m[38;5;124m"[39m,
[1;32m    219[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__qualname__[39m[38;5;132;01m}[39;00m[38;5;124m must be[39m[38;5;124m"[39m,
[1;32m    220[0m         [38;5;28mstr[39m(e),
[1;32m    221[0m     )

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/sklearn/tree/_export.py:196[0m, in [0;36mplot_tree[0;34m(decision_tree, max_depth, feature_names, class_names, label, filled, impurity, node_ids, proportion, rounded, precision, ax, fontsize)[0m
[1;32m     77[0m [38;5;129m@validate_params[39m(
[1;32m     78[0m     {
[1;32m     79[0m         [38;5;124m"[39m[38;5;124mdecision_tree[39m[38;5;124m"[39m: [DecisionTreeClassifier, DecisionTreeRegressor],
[0;32m   (...)[0m
[1;32m    109[0m     fontsize[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    110[0m ):
[1;32m    111[0m [38;5;250m    [39m[38;5;124;03m"""Plot a decision tree.[39;00m
[1;32m    112[0m 
[1;32m    113[0m [38;5;124;03m    The sample counts that are shown are weighted with any sample_weights that[39;00m
[0;32m   (...)[0m
[1;32m    193[0m [38;5;124;03m    [...][39;00m
[1;32m    194[0m [38;5;124;03m    """[39;00m
[0;32m--> 196[0m     check_is_fitted(decision_tree)
[1;32m    198[0m     exporter [38;5;241m=[39m _MPLTreeExporter(
[1;32m    199[0m         max_depth[38;5;241m=[39mmax_depth,
[1;32m    200[0m         feature_names[38;5;241m=[39mfeature_names,
[0;32m   (...)[0m
[1;32m    209[0m         fontsize[38;5;241m=[39mfontsize,
[1;32m    210[0m     )
[1;32m    211[0m     [38;5;28;01mreturn[39;00m exporter[38;5;241m.[39mexport(decision_tree, ax[38;5;241m=[39max)

File [0;32m/opt/homebrew/Caskroom/miniconda/base/envs/python311/lib/python3.11/site-packages/sklearn/utils/validation.py:1462[0m, in [0;36mcheck_is_fitted[0;34m(estimator, attributes, msg, all_or_any)[0m
[1;32m   1459[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m is not an estimator instance.[39m[38;5;124m"[39m [38;5;241m%[39m (estimator))
[1;32m   1461[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m _is_fitted(estimator, attributes, all_or_any):
[0;32m-> 1462[0m     [38;5;28;01mraise[39;00m NotFittedError(msg [38;5;241m%[39m {[38;5;124m"[39m[38;5;124mname[39m[38;5;124m"[39m: [38;5;28mtype[39m(estimator)[38;5;241m.[39m[38;5;18m__name__[39m})

[0;31mNotFittedError[0m: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

